services:
  - type: web
    name: boamp-scraper
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: tenders_db
      - key: MONGO_COLLECTION
        value: tenders_boamp
      - key: API_EMAIL
        sync: false
      - key: API_PASSWORD
        sync: false
